### ISSUE TITLE
java.lang.NullPointerException on rapid request issuing

### ISSUE THREAD

**Issue by cosminbasca** [rapidoid/rapidoid#54] opened 2016-03-24 13:13 UTC
when I issue multiple requests at the same time (roughly) say press the refresh button in the browser in rapid succession I am seeing this stacktrace in the console:

ERROR | pool-1-thread-7 | org.rapidoid.job.ContextPreservingJobWrapper | Job execution failed! | message=null
java.lang.NullPointerException
	at org.rapidoid.net.impl.RapidoidWorker.close(RapidoidWorker.java:261)
	at org.rapidoid.net.impl.RapidoidWorker.close(RapidoidWorker.java:256)
	at org.rapidoid.net.impl.RapidoidConnection.close(RapidoidConnection.java:229)
	at org.rapidoid.net.impl.RapidoidConnection.close(RapidoidConnection.java:276)
	at org.rapidoid.net.impl.RapidoidConnection.closeIf(RapidoidConnection.java:283)
	at org.rapidoid.net.impl.RapidoidConnection.closeIf(RapidoidConnection.java:45)
	at org.rapidoid.http.fast.FastHttp.done(FastHttp.java:458)
	at org.rapidoid.http.fast.ReqImpl.finish(ReqImpl.java:516)
	at org.rapidoid.http.fast.ReqImpl.onDone(ReqImpl.java:430)
	at org.rapidoid.http.fast.ReqImpl.done(ReqImpl.java:414)
	at org.rapidoid.http.fast.handler.AbstractAsyncHttpHandler.complete(AbstractAsyncHttpHandler.java:205)
	at org.rapidoid.http.fast.handler.AbstractAsyncHttpHandler$1.run(AbstractAsyncHttpHandler.java:128)
	at org.rapidoid.job.ContextPreservingJobWrapper.run(ContextPreservingJobWrapper.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1-thread-7" java.lang.RuntimeException: Job execution failed!
	at org.rapidoid.u.U.rte(U.java:560)
	at org.rapidoid.job.ContextPreservingJobWrapper.run(ContextPreservingJobWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.rapidoid.net.impl.RapidoidWorker.close(RapidoidWorker.java:261)
	at org.rapidoid.net.impl.RapidoidWorker.close(RapidoidWorker.java:256)
	at org.rapidoid.net.impl.RapidoidConnection.close(RapidoidConnection.java:229)
	at org.rapidoid.net.impl.RapidoidConnection.close(RapidoidConnection.java:276)
	at org.rapidoid.net.impl.RapidoidConnection.closeIf(RapidoidConnection.java:283)
	at org.rapidoid.net.impl.RapidoidConnection.closeIf(RapidoidConnection.java:45)
	at org.rapidoid.http.fast.FastHttp.done(FastHttp.java:458)
	at org.rapidoid.http.fast.ReqImpl.finish(ReqImpl.java:516)
	at org.rapidoid.http.fast.ReqImpl.onDone(ReqImpl.java:430)
	at org.rapidoid.http.fast.ReqImpl.done(ReqImpl.java:414)
	at org.rapidoid.http.fast.handler.AbstractAsyncHttpHandler.complete(AbstractAsyncHttpHandler.java:205)
	at org.rapidoid.http.fast.handler.AbstractAsyncHttpHandler$1.run(AbstractAsyncHttpHandler.java:128)
	at org.rapidoid.job.ContextPreservingJobWrapper.run(ContextPreservingJobWrapper.java:62)
	... 3 more

The reply seems to arrive just fine in the browser but I am wondering if this behavior is caused by my handler or an actual bug in the server. 

Thanks !

**Comment by pmella** [comment] 2016-04-12 04:24
Same issue here. 

in my case I have the following controller:

`@Controller
  public class NoBullshit { 
@GET
  public String hello() { return "Hello Wold";}}`

**Comment by fourcube** [comment] 2016-04-21 13:48
Which version of rapidoid are you using? I couldn't reproduce this with neither the current master nor 5.0.12.

**Comment by cosminbasca** [comment] 2016-04-21 13:55
I am using 5.0.12

**Comment by fourcube** [comment] 2016-04-21 13:59
Which JVM are you using to run your application? (`java -version`)

**Comment by cosminbasca** [comment] 2016-04-21 14:05
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Comment by cosminbasca** [comment] 2016-04-23 10:00
this is great @fourcube ! Thanks for the help and info, looking forward for 5.1.0 to be released

**Comment by pmella** [comment] 2016-04-29 18:37
Thanks! @fourcube, just to give you more information, this is very easy to replicate. The only thing you have to do is to keep pressed the CTRL+R key combination on chrome, then the issue will appear after some requests.

**Comment by nmihajlovski** [comment] 2016-05-16 21:26
Apologies for the very late reply. This has been fixed in the recent release of v5.1.0.

**Closed by nmihajlovski** 2016-05-16 21:26 UTC
Labels: bug
